// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProContractReplayResult } from "./ProContractReplayResult";
import type { ProContractSubject } from "./ProContractSubject";

export type ProContractHandoff = { summary: string, uncertainties: Array<string>, subject: ProContractSubject, replay: ProContractReplayResult | null, createdAt: bigint, };
