// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ProContractReplayResult = { policyHash: string, subjectHash: string, evidenceHash: string, passed: boolean, summary: string, };
