// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProContractChallengeDisclosure } from "./ProContractChallengeDisclosure";

export type ProContractChallenge = { revision: bigint, subjectHash: string, evidenceHash: string, disclosure: ProContractChallengeDisclosure, summary: string | null, createdAt: bigint, attestationId: string | null, };
