// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ProContractBudget = { turns: bigint, actions: bigint,
/**
 * Absolute Unix time in seconds.
 */
deadlineAt: bigint, };
