// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProContractProtectedFile } from "./ProContractProtectedFile";
import type { ProContractReplayCheck } from "./ProContractReplayCheck";

export type ProContractReplayPolicy = { checks: Array<ProContractReplayCheck>, protected: Array<ProContractProtectedFile>, artifacts: Array<string>, };
