// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProContractBudget } from "./ProContractBudget";
import type { ProContractEvidence } from "./ProContractEvidence";
import type { ProContractRequirement } from "./ProContractRequirement";
import type { ProContractResolution } from "./ProContractResolution";
import type { ProContractTrigger } from "./ProContractTrigger";

export type ProContractSpec = { trigger: ProContractTrigger, goal: string, brief: string, artifacts: Array<string>, requires: Array<ProContractRequirement>, authority: Array<string>, budget: ProContractBudget, evidence: ProContractEvidence, resolution: ProContractResolution, };
