// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ProContractExecutionInfo = { contractId: string, revision: bigint, executorThreadId: string | null, executionPolicy: string | null, dispatched: boolean, awaitingRevisionDecision: boolean, attempts: bigint, turnsUsed: bigint, actionsUsed: bigint,
/**
 * Absolute Unix time in seconds, or zero when immediately runnable.
 */
nextActionAt: bigint, turnsLimit: bigint, actionsLimit: bigint,
/**
 * Absolute Unix time in seconds.
 */
deadlineAt: bigint, maxAttempts: bigint, leaseOwner: string | null,
/**
 * Absolute Unix time in seconds, or zero when no lease is held.
 */
leaseExpiresAt: bigint, };
