// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProContractBlocked } from "./ProContractBlocked";
import type { ProContractChallenge } from "./ProContractChallenge";
import type { ProContractEscalation } from "./ProContractEscalation";
import type { ProContractHandoff } from "./ProContractHandoff";
import type { ProContractPendingRevision } from "./ProContractPendingRevision";
import type { ProContractSpec } from "./ProContractSpec";
import type { ProContractStatus } from "./ProContractStatus";

export type ProContractInfo = { id: string, scope: string, spec: ProContractSpec, issuer: string, executor: string, specHash: string, revision: bigint, status: ProContractStatus, blocked: ProContractBlocked | null, handoff: ProContractHandoff | null, challenge: ProContractChallenge | null, pendingRevision: ProContractPendingRevision | null, attestationId: string | null, escalation: ProContractEscalation | null, };
